CREATE TABLE `tblleave` (
  `LeaveID` INT NOT NULL AUTO_INCREMENT,
  `EmployeeID` INT NOT NULL,
  `DayOffStart` DATE DEFAULT NULL,
  `DayOffEnd` DATE DEFAULT NULL,
  `LeaveType` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`LeaveID`),
  CONSTRAINT `fk_EmployeeID`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `tblqlnv` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
ALTER TABLE tblleave
MODIFY COLUMN LeaveType INT DEFAULT NULL;
ALTER TABLE tblleave
ADD COLUMN ApprovalStatus ENUM('pending', 'approved', 'rejected') DEFAULT 'pending';
ALTER TABLE tblleave
MODIFY COLUMN DayOffStart DATETIME;

ALTER TABLE tblleave
MODIFY COLUMN DayOffEnd DATETIME;

-- ALTER TABLE tblqlnv
-- ADD COLUMN RemainingLeaveDays INT DEFAULT 20;

